### ISSUE TITLE
Request - Official STM32 Core

### ISSUE THREAD

**Issue by tomvdb** [rogerclarkmelbourne/WS2812B_STM32_Libmaple#1]
Hi,

Would it be possible to adapt this to the new stm32 arduino core so that it can be used on other stm32 processors as well ?

T

**Comment by rogerclarkmelbourne** [comment]
The code would need to be completely re-written to use the internal functions inside the STM HAL.

So although it is possible, its outside of the scope of why I wrote it, i.e to work with LibMaple
