### ISSUE TITLE
Interoperability with W5500 Ethernet

### ISSUE THREAD

**Issue by AussieMakerGeek** [rogerclarkmelbourne/WS2812B_STM32_Libmaple#7]
I'm trying to find a solution that will allow me to utilize a W5500 Ethernet module and be able to control WS2812b LEDs at the same time.

As these both use SPI (and default to SPI1) They don't play nice together.

I found this library - https://github.com/stevstrong/Ethernet_STM32 which allows me to migrate over to SPI2 for the Ethernet module but as soon as I call the show() function, the Ethernet module stops working.

Independently, both work fine.

I have gone over the code of both libraries and nothing looks as if it should be interfering - Can you shed any light?

**Comment by rogerclarkmelbourne** [comment]
Not  bug.
