### ISSUE TITLE
Using second STM32F103C8T6 (bluepill) SPI

### ISSUE THREAD

**Issue by Kubasz091** [rogerclarkmelbourne/WS2812B_STM32_Libmaple#9]
So, I want to use second STM32F103C8T6 (bluepill) SPI line to drive LEDs, but i don't know to achieve this with your library. It is working great on first, but unfortunately it is already used by NRF24L01 module in my project. I'd be rally grateful if you'd help me to solve this problem.
I tried this: https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/536 , but your library automaticaly sets SPI1 line as default.

**Comment by rogerclarkmelbourne** [comment]
Not a bug. 

Try https://www.stm32duino.com
